// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LongPressController from "./long_press_controller"
application.register("long-press", LongPressController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PostActionsController from "./post_actions_controller"
application.register("post-actions", PostActionsController)

import PullToRefreshController from "./pull_to_refresh_controller"
application.register("pull-to-refresh", PullToRefreshController)

import ScreenReaderController from "./screen_reader_controller"
application.register("screen-reader", ScreenReaderController)

import SourceFiltersController from "./source_filters_controller"
application.register("source-filters", SourceFiltersController)

import SwipeActionsController from "./swipe_actions_controller"
application.register("swipe-actions", SwipeActionsController)

import TouchFeedbackController from "./touch_feedback_controller"
application.register("touch-feedback", TouchFeedbackController)

import VirtualScrollController from "./virtual_scroll_controller"
application.register("virtual-scroll", VirtualScrollController)
