// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or remove an existing
// one to update the manifest.

import { application } from "./application"

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import LongPressController from "./long_press_controller"
application.register("long-press", LongPressController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import PostActionsController from "./post_actions_controller"
application.register("post-actions", PostActionsController)

import PullToRefreshController from "./pull_to_refresh_controller"
application.register("pull-to-refresh", PullToRefreshController)

import SwipeActionsController from "./swipe_actions_controller"
application.register("swipe-actions", SwipeActionsController)

import TouchFeedbackController from "./touch_feedback_controller"
application.register("touch-feedback", TouchFeedbackController)

console.log("✅ All Stimulus controllers registered")