default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        cleanup_old_posts:
          class: CleanupOldPostsJob
          schedule: "every day at 3am"

  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  workers:
    - queues: "*"
      threads: 5
      processes: 2
      polling_interval: 0.1